### ISSUE TITLE
Parallel edges and curved arrows

### ISSUE THREAD

**Issue by andyle13** [sim51/react-sigma#24]
Hi, may I ask if it's possible to have curved arrows and parallel edges in @react-sigma? As far as I have tried out the library, it appears that having multiple edges between two nodes will result in a white screen with an error message prompting that two nodes can only have one edge. For my use case, it would be of great importance, especially with curved arrows for presenting multiple edges between two nodes in a well-readable way.

[@dunnock/react-sigma has support for it](https://dunnock.github.io/react-sigma/?path=/story/plugins--edge-labels), though I reckon that adding these features would significantly facilitate the use of Sigma in React.

**Comment by sim51** [comment]
For the error you've got, I assume it comes from your graphology instance.

When you create a graph with graphology you have to specify :
- allowSelfLoops [boolean] true: should the graph allow self-loops?
-  multi [boolean] false: Should the graph allow parallel edges?
-  type [string] “mixed”: Type of the graph. One of directed, undirected or mixed.

As you can see, per default multi is false.

In react-sigma, the property `graph` of the component `SigmaContainer` is either a graphology instance, or a graph constructor : 
https://sim51.github.io/react-sigma/docs/api/core/interfaces/SigmaContainerProps#graph

Perhaps I should add an example for that..

For curved edges, for now it doesn't exist in Sigma v2.

**Comment by andyle13** [comment]
Ahhh I see... I wasn't aware of the options available in `graphology` so thanks for pointing it out for me! I have been trying to add parallel edges purely in Node.js which seems to work fine after setting `multi` to `true`. The same applies to my React app until I'm trying to load the graph via the `useLoadGraph` hook which seems to force `graphology` to throw an error stating that I have to set `multi` to `true` which has already been done in this instance. Nonetheless, graphology works with parallel edges by commenting out the hook, though it does not render the graph on Sigma in return. 🤔

Here is the error (`multi` is `true`):
```
Uncaught (in promise) UsageGraphError: Graph.addDirectedEdgeWithKey: an edge linking "http://www.asdf.com/graph#Diagram-35b0e713-1b2c-4ef7-bcc9-f698823d515b" to "http://www.asdf.com/graph#Package-fe00adf1-7630-420a-b1e0-4b8cd336b815" already exists. If you really want to add multiple edges linking those nodes, you should create a multi graph by using the 'multi' option.
    at Ct (graphology.umd.min.js:1:1)
    at r.t.generateKey.Wt.<computed> [as addDirectedEdgeWithKey] (graphology.umd.min.js:1:1)
    at graphology.umd.min.js:1:1
    at dt (graphology.umd.min.js:1:1)
    at r.t.<computed> [as forEachEdge] (graphology.umd.min.js:1:1)
    at r.i.import (graphology.umd.min.js:1:1)
    at useLoadGraph.ts:22:1
    at GraphCanvas.tsx:40:1
```

**Comment by sim51** [comment]
Can you create an example on codesandbox that reproduce your issue ?

**Comment by andyle13** [comment]
Unfortunately I am unable to access codesandbox due to corporate firewall, though what I can do is sharing the four files underneath that have been anonymised at the very least. I hope that is okay for you?

`Major dependencies from package.json`
```
"react": "^17.0.2"
"react-dom": "^17.0.2"
"react-scripts": "5.0.0"
"@react-sigma/core": "^2.0.2"
"graphology": "^0.24.1"
"sigma": "^2.2.0"
```

`GraphContainer.tsx`
```
import {
  ControlsContainer,
  FullScreenControl,
  SigmaContainer,
  ZoomControl,
} from '@react-sigma/core'

import { BiRadioCircleMarked } from 'react-icons/bi'
import {
  BsArrowsFullscreen,
  BsFullscreenExit,
  BsZoomIn,
  BsZoomOut,
} from 'react-icons/bs'
import { GraphContainerParams } from '../types/components'
import { defaultGraphConfig } from '../utils/sigma'
import { GraphCanvas } from './GraphCanvas'

export const GraphContainer = ({
  containerHeight,
}: GraphContainerParams) => (
  <SigmaContainer
    style={{ height: containerHeight }}
    initialSettings={defaultGraphConfig}
  >
    <GraphCanvas />
    <ControlsContainer>
      <FullScreenControl>
        <BsArrowsFullscreen />
        <BsFullscreenExit />
      </FullScreenControl>
      <ZoomControl>
        <BsZoomIn />
        <BsZoomOut />
        <BiRadioCircleMarked />
      </ZoomControl>
    </ControlsContainer>
  </SigmaContainer>
)
```

`GraphCanvas.tsx`
```
import { useLoadGraph, useRegisterEvents, useSigma } from '@react-sigma/core'
import React, { useEffect, useState } from 'react'
import { dataset } from '../data/graphData'

import {
  forceAtlas2Layout,
  getGraphContext,
  loadNodesAndEdgesToGraph,
  shiftNodeCoordinates,
} from '../utils/sigma'

export const GraphCanvas: React.FC<> = () => {
  const graph = getGraphContext()
  const sigma = useSigma()

  const registerEvents = useRegisterEvents()
  const loadGraph = useLoadGraph()

  const [prevNode, setPrevNode] = useState<string>(null)

  let draggedNode: string | null = null

  useEffect(() => {
    const { nodes, edges } = dataset

    loadNodesAndEdgesToGraph(nodes, edges)
    forceAtlas2Layout()
    loadGraph(graph)
  }, [loadGraph])

  useEffect(() => {
    registerEvents({
      downNode: (event) => {
        draggedNode = event.node
        graph.setNodeAttribute(draggedNode, 'highlighted', true)
        sigma.getCamera().disable()
      },
      mousemove: (event) => {
        if (draggedNode) {
          shiftNodeCoordinates(event, sigma, draggedNode)
          loadGraph(graph)
        }
      },
      mouseup: () => {
        if (draggedNode) {
          graph.removeNodeAttribute(draggedNode, 'highlighted')
        }

        draggedNode = null
        sigma.getCamera().enable()
      },
    })
  }, [loadGraph, registerEvents])

  return null
}
```

`sigma.ts`
```
import Graph from 'graphology'
import Sigma from 'sigma'
import { Settings } from 'sigma/settings'
import { MouseCoords } from 'sigma/types'
import { SigmaInputNode, SigmaInputEdge } from '../types/graph'
import { Colour } from './enum'

const graphContext = new Graph({
  multi: true,
})

export const getGraphContext = () => graphContext

export const defaultGraphConfig: Partial<Settings> = {
  renderEdgeLabels: true,
  defaultEdgeColor: Colour.Gray,
  defaultEdgeType: 'arrow',
  labelWeight: 'bold',
  edgeLabelWeight: 'bold',
  edgeLabelColor: { color: Colour.Black },
  edgeLabelSize: 10,
  labelSize: 12,
  defaultNodeColor: Colour.Yellow,
}

export const allocateNodeOnCanvas = (nodeId: string, nodeNumber: number) => {
  const graph = getGraphContext()

  const angle = (nodeNumber * 2 * Math.PI) / graph.order
  graph.setNodeAttribute(nodeId, 'x', 100 * Math.cos(angle))
  graph.setNodeAttribute(nodeId, 'y', 100 * Math.sin(angle))
}

export const loadNodesAndEdgesToGraph = (
  nodes: SigmaInputNode[],
  edges: SigmaInputEdge[]
) => {
  const graph = getGraphContext()

  graph.clear()

  nodes.forEach(({ id, ...rest }) => graph.addNode(id, rest))
  edges.forEach(({ src, dst, ...rest }) => {
    if (!dst.includes('#Model-')) {
      graph.addEdge(src, dst, rest)
    }
  })

  graph.nodes().forEach((nodeId: string, nodeNumber: number) => {
    allocateNodeOnCanvas(nodeId, nodeNumber)
  })
}

export const shiftNodeCoordinates = (
  event: MouseCoords,
  sigma: Sigma,
  draggedNode: string
) => {
  const graph = getGraphContext()

  const { x, y } = sigma.viewportToGraph(event)

  graph.setNodeAttribute(draggedNode, 'x', x)
  graph.setNodeAttribute(draggedNode, 'y', y)
}
```

`graphData.ts`
```
export const dataset = {
  nodes: [
    {
      id: 'http://www.asdf.com/graph#Bank',
      size: 10,
      label: 'Bank',

      properties: [
        {
          name: 'name',
          datatype: 'Literal',
        },
        {
          name: 'established in',
          datatype: 'Literal',
        },
        {
          name: 'valuation',
          datatype: 'Literal',
        },
        {
          name: 'currency',
          datatype: 'Literal',
        },
      ],
    },
    {
      id: 'http://www.asdf.com/graph#Account',
      size: 10,
      label: 'Account',

      properties: [
        {
          name: 'balance',
          datatype: 'Literal',
        },
        {
          name: 'overdraft',
          datatype: 'Literal',
        },
        {
          name: 'credit',
          datatype: 'Literal',
        },
        {
          name: 'type',
          datatype: 'Literal',
        },
      ],
    },
    {
      id: 'http://www.asdf.com/graph#Customer',
      size: 10,
      label: 'Customer',

      properties: [
        {
          name: 'name',
          datatype: 'Literal',
        },
        {
          name: 'dob',
          datatype: 'Literal',
        },
      ],
    },
    {
      id: 'http://www.asdf.com/graph#Card',
      size: 10,
      label: 'Card',

      properties: [
        {
          name: 'name',
          datatype: 'Literal',
        },
        {
          name: 'mmyy',
          datatype: 'Literal',
        },
        {
          name: 'cvv',
          datatype: 'Literal',
        },
        {
          name: 'number',
          datatype: 'Literal',
        },
      ],
    },
    {
      id: 'http://www.asdf.com/graph#HUV',
      size: 10,
      label: 'HUV',
    },
    {
      id: 'http://www.asdf.com/graph#PowerSubsystem',
      size: 10,
      label: 'PowerSubsystem',
    },
    {
      id: 'http://www.asdf.com/graph#BrakeSubsystem',
      size: 10,
      label: 'BrakeSubsystem',
    },
    {
      id: 'http://www.asdf.com/graph#BrakeDisk',
      size: 10,
      label: 'BrakeDisk',
    },
    {
      id: 'http://www.asdf.com/graph#BrakePedal',
      size: 10,
      label: 'BrakePedal',
    },
  ],
  edges: [
    {
      src: 'http://www.asdf.com/graph#Account',
      dst: 'http://www.asdf.com/graph#Bank',
      label: 'managed by',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#Card',
      dst: 'http://www.asdf.com/graph#Bank',
      label: 'supplied by',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#Card',
      dst: 'http://www.asdf.com/graph#Customer',
      label: 'owned by',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#Account',
      dst: 'http://www.asdf.com/graph#Customer',
      label: 'owned by',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#HUV',
      dst: 'http://www.asdf.com/graph#BrakeSubsystem',
      label: 'brakeSubsystem',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#HUV',
      dst: 'http://www.asdf.com/graph#PowerSubsystem',
      label: 'powerSubsystem',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#BrakeSubsystem',
      dst: 'http://www.asdf.com/graph#BrakeDisk',
      label: 'leftBrakeDisk',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#BrakeSubsystem',
      dst: 'http://www.asdf.com/graph#BrakeDisk',
      label: 'rightBrakeDisk',
      size: 4,
    },
    {
      src: 'http://www.asdf.com/graph#BrakeSubsystem',
      dst: 'http://www.asdf.com/graph#BrakePedal',
      label: 'brakePedal',
      size: 4,
    },
  ],
}
```

**Comment by sim51** [comment]
You didn't pass the MultiDirectedGraph constructor to the SigmaContainer, that's your mistake.

I created an example here https://github.com/sim51/react-sigma/tree/main/packages/examples/src/views/multidirectedgraph

**Comment by andyle13** [comment]
Brilliant, it works! Thanks for your help! 👍

**Comment by sim51** [comment]
- An example has been created : https://github.com/sim51/react-sigma/tree/main/packages/examples/src/views/multidirectedgraph
- Documentation on the statup example has been improve : https://sim51.github.io/react-sigma/docs/start-setup#graph-constructor
- A question on it has been added in the FAQ : https://sim51.github.io/react-sigma/docs/faq#how-i-can-correct-the-error-graphaddedge-an-edge-linking-x-to-y-already-exists-if-you-really-want-to-add-multiple-edges-linking-those-nodes-you-should-create-a-multi-graph-by-using-the-multi-option

**Comment by solarconstant** [comment]
Hi. I am facing this issue while trying to render a graph by parsing a GEXF file/string.
This is the error I'm getting:
```ERROR
Graph.addDirectedEdgeWithKey: an edge linking "1" to "2" already exists. If you really want to add multiple edges linking those nodes, you should create a multi graph by using the 'multi' option.
```

I have added the MultiDirectedGraph constructor to the sigma container and parsed the gexf using this constructor. Even tried to add {multi:true} there, but to no success.

```const LoadGraph = () => {
        const loadGraph = useLoadGraph();

        useEffect(() => {
                const graph = parse(MultiDirectedGraph, ``, {multi:true})
                loadGraph(graph);
        }, [loadGraph]);

        return null;
};
```

How do I correctly render this graph from the gexf string. if it has multiple edges between same nodes.

**Comment by sim51** [comment]
You need to add the graphology  constructor on the `SigmaContainer` like in this example : https://sim51.github.io/react-sigma/docs/start-setup#graph-constructor

**Comment by solarconstant** [comment]
I have replicated the issue here:
[Sandbox](https://codesandbox.io/p/sandbox/multi-graph-gexf-qwwvdp?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clze0rcbm00063j6i5vj2wa2d%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clze0rcbl00023j6i700p1xgc%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clze0rcbl00033j6i7whjhasu%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clze0rcbl00053j6ikkosnbgz%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clze0rcbl00023j6i700p1xgc%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clze0rcbk00013j6id2iqcij8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clze0rcbl00023j6i700p1xgc%2522%252C%2522activeTabId%2522%253A%2522clze0rcbk00013j6id2iqcij8%2522%257D%252C%2522clze0rcbl00053j6ikkosnbgz%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clze0rcbl00043j6i3rf7wvi4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%255D%252C%2522id%2522%253A%2522clze0rcbl00053j6ikkosnbgz%2522%252C%2522activeTabId%2522%253A%2522clze0rcbl00043j6i3rf7wvi4%2522%257D%252C%2522clze0rcbl00033j6i7whjhasu%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clze0rcbl00033j6i7whjhasu%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)


Even adding {multi: true} to the constructor doesn't seem to help.

**Comment by solarconstant** [comment]
Any idea on how this can be solved? Or any workaround?

**Comment by solarconstant** [comment]
Hey. I think I figured it out.
I was initializing the graph using the MultiDirectedGraph constructor, something like this:
```const graph = new Graph({ multi: true });```

And then passing the same as the graph attr. to the SigmaContainer component:
```<SigmaContainer graph={MultiDirectedGraph} />```

Turns out, I needed to initialize the graph using the Graph constructor and then pass the MultiDirectedGraph to the SigmaContainer component.

```const graph = new Graph({ multi: true });```

 ```
<SigmaContainer style={sigmaStyle} graph={MultiDirectedGraph} settings={{
    allowInvalidContainer: true, edgeProgramClasses: {
        curved: EdgeCurveProgram,
        straight: EdgeCurveProgram
    }
}}>
    <LoadGraph />
</SigmaContainer>
```

And then, to parse a GEXF file, as I was doing in my case, I did this:
```
const graph = parse(Graph, `<GEXF>`);
graph.setAttribute("multi", true);
```

Although this seems to work, it would be great if you could validate this.

**Comment by sim51** [comment]
In your example you have `import MultiDirectedGraph from "graphology";` which is bad.
The default export of graphology is the `Graph` constructor (even if you named it MultiDirectedGraph ...)

SO you should replace it by `import { MultiDirectedGraph } from "graphology";`
