### ISSUE TITLE
Display mixed node type doesn't work

### ISSUE THREAD

**Issue by BaherZ** [sim51/react-sigma#33]
- React-sigma-v2 version: ^3.0.3"
- Sigma.js version : "^2.3.1"
- Graphology version : "^0.25.0"
- Operating system: Ubuntu 20.04
- Web browser: chrome 106.0.5249.103 (64-bit)
----------------------------------

**Steps to reproduce**
- Have a graph with multiple types (circle, image, etc) leads to error, in my specific example, it was a mix of image nodes and regular/circle nodes

**Expected behavior**

Image nodes would show as images
Regular/Circle nodes would show as circles

**Actual behavior**

Exactly the same error as the one reported in this ticket: https://github.com/sim51/react-sigma/issues/32#issuecomment-1282545745

Uncaught TypeError: Cannot read properties of undefined (reading 'process')
at Sigma.process (sigma.js?2055:622:1)
at Sigma._refresh (sigma.js?2055:698:1)
at Sigma.refresh (sigma.js?2055:1191:1)
Additionally, include (as appropriate) console logs, stacktraces, screenshots, and other debug info.

**Comment by sim51** [comment]
I did an example that works 
Take a look here : https://codesandbox.io/s/react-sigma-example-qlkqg8

In fact you have to define the full list of program that you want to use (in the example circle & image), otherwise there is an issue.
But in the next version of sigma (probably the 2.4) if you provide a list program, it will be merged with the default (see this commit https://github.com/jacomyal/sigma.js/commit/d318cf63c983ba8b2d613b876ccc6f84c37f5b55 )

**Comment by BaherZ** [comment]
Fixed, thanks, and looking forward to the next version :)
