### ISSUE TITLE
useRegisterEvents triggers re-renders

### ISSUE THREAD

**Issue by twall** [sim51/react-sigma#63]
`useRegisterEvents` if used as in the hooks example triggers endless re-renders.  it must be put within a `useEffect` function to prevent re-renders.

- React-sigma-v2 version: 3.4.2
- **Steps to reproduce**

```
const MyComponent = (props) => {
  const registerEvents = useRegisterEvents();
  registerEvents({});
  ...
  return <div />;
};
```

- Expected behavior
Events should be registered, and deregistered when the component is unmounted.  I should be able to call `registerEvents` without having to memoize the object passed in.  It should probably be doing a deep compare of its argument.

- Actual behavior
`useRegisterEvents` returns its useState setter function, and uses `useEffect` with a dependency of the object passed to `registerEvents`.  This means that the `useEffect` function's argument will be run on _every_ call to `MyComponent`, since the object passed in has a different identity.

**Comment by sim51** [comment]
The `registerEvents` should be used in a `useEffect` like in this example:  https://github.com/sim51/react-sigma/blob/main/project/packages/examples/src/views/events.tsx

If you want to use it directly in your component, you must use the `useMemo` hook for the settings, to avoid the change th ref of the object. 

This is the expected behavior, which respect the react way.

**Comment by twall** [comment]
You should probably update the docs at
https://sim51.github.io/react-sigma/docs/api/core/#useregisterevents to
reflect that usage.

**Comment by sim51** [comment]
Agree, this code comment (which is used to generate this doc) should be changed.

**Comment by twall** [comment]
Thanks for the clarification.

**Comment by sim51** [comment]
TS doc has been updated, and so the doc on the website
